/**
 * Bottom pagination links show the page's full `title`, which is written for
 * search results and runs long. Swap in the `sidebarTitle` so the previous and
 * next links read the same as the sidebar entries they point at.
 *
 * SIDEBAR_TITLES mirrors the `sidebarTitle` frontmatter of every .mdx page.
 * tests/validate-reference-style.mjs fails if the two drift apart.
 */
const SIDEBAR_TITLES = {
  "/": "Home",
  "/api-reference/authentication": "Authentication",
  "/api-reference/chat-completions": "Chat Completions",
  "/api-reference/embeddings": "Embeddings",
  "/api-reference/errors": "Errors",
  "/api-reference/image-generation": "Images API",
  "/api-reference/models": "Models",
  "/api-reference/overview": "Overview",
  "/api-reference/responses": "Responses",
  "/api-reference/seedance-video-generation": "Seedance Video Generation",
  "/dashboard/api-keys": "API Keys",
  "/dashboard/top-up": "Top Up",
  "/dashboard/usage": "Usage",
  "/de": "Startseite",
  "/de/api-reference/authentication": "Authentifizierung",
  "/de/api-reference/chat-completions": "Chat Completions",
  "/de/api-reference/embeddings": "Embeddings",
  "/de/api-reference/errors": "Fehler",
  "/de/api-reference/image-generation": "Images API",
  "/de/api-reference/models": "Modelle",
  "/de/api-reference/overview": "Übersicht",
  "/de/api-reference/responses": "Responses",
  "/de/api-reference/seedance-video-generation": "Seedance Videogenerierung",
  "/de/dashboard/api-keys": "API-Schlüssel",
  "/de/dashboard/top-up": "Aufladen",
  "/de/dashboard/usage": "Nutzung",
  "/de/guides/anthropic-sdk": "Anthropic SDK",
  "/de/guides/api-access": "API-Zugang",
  "/de/guides/claude-code": "Claude Code",
  "/de/guides/codex-cli": "Codex CLI",
  "/de/guides/codex-desktop": "Codex Desktop",
  "/de/guides/flatkey-cli": "Flatkey CLI mit KI-Agent",
  "/de/guides/image-generation": "Bildgenerierung & -bearbeitung",
  "/de/guides/minimax-h3": "MiniMax H3",
  "/de/guides/openai-sdk": "OpenAI SDK",
  "/de/guides/seedance": "Seedance",
  "/de/guides/text-generation": "Textgenerierung",
  "/de/guides/video-generation": "Videogenerierung",
  "/de/introduction": "Einführung",
  "/de/quickstart": "Schnellstart",
  "/de/reference/enterprise": "Enterprise",
  "/de/reference/faq": "FAQ",
  "/de/reference/model-health": "Modell-Gesundheit",
  "/de/reference/model-list": "Modellliste",
  "/de/reference/pricing": "Preise",
  "/es": "Inicio",
  "/es/api-reference/authentication": "Autenticación",
  "/es/api-reference/chat-completions": "Chat Completions",
  "/es/api-reference/embeddings": "Embeddings",
  "/es/api-reference/errors": "Errores",
  "/es/api-reference/image-generation": "API de Imágenes",
  "/es/api-reference/models": "Modelos",
  "/es/api-reference/overview": "Descripción general",
  "/es/api-reference/responses": "Responses",
  "/es/api-reference/seedance-video-generation": "Generación de vídeo Seedance",
  "/es/dashboard/api-keys": "Claves API",
  "/es/dashboard/top-up": "Recargar",
  "/es/dashboard/usage": "Uso",
  "/es/guides/anthropic-sdk": "SDK de Anthropic",
  "/es/guides/api-access": "Acceso a la API",
  "/es/guides/claude-code": "Claude Code",
  "/es/guides/codex-cli": "Codex CLI",
  "/es/guides/codex-desktop": "Codex Desktop",
  "/es/guides/flatkey-cli": "CLI de Flatkey con agente de IA",
  "/es/guides/image-generation": "Generación y edición de imágenes",
  "/es/guides/minimax-h3": "MiniMax H3",
  "/es/guides/openai-sdk": "SDK de OpenAI",
  "/es/guides/seedance": "Seedance",
  "/es/guides/text-generation": "Generación de texto",
  "/es/guides/video-generation": "Generación de video",
  "/es/introduction": "Introducción",
  "/es/quickstart": "Inicio rápido",
  "/es/reference/enterprise": "Empresa",
  "/es/reference/faq": "Preguntas frecuentes",
  "/es/reference/model-health": "Estado del Modelo",
  "/es/reference/model-list": "Lista de modelos",
  "/es/reference/pricing": "Precios",
  "/fr": "Accueil",
  "/fr/api-reference/authentication": "Authentification",
  "/fr/api-reference/chat-completions": "Chat Completions",
  "/fr/api-reference/embeddings": "Embeddings",
  "/fr/api-reference/errors": "Erreurs",
  "/fr/api-reference/image-generation": "API Images",
  "/fr/api-reference/models": "Modèles",
  "/fr/api-reference/overview": "Vue d'ensemble",
  "/fr/api-reference/responses": "Responses",
  "/fr/api-reference/seedance-video-generation": "Génération de vidéos Seedance",
  "/fr/dashboard/api-keys": "Clés API",
  "/fr/dashboard/top-up": "Recharge",
  "/fr/dashboard/usage": "Utilisation",
  "/fr/guides/anthropic-sdk": "SDK Anthropic",
  "/fr/guides/api-access": "Accès API",
  "/fr/guides/claude-code": "Claude Code",
  "/fr/guides/codex-cli": "Codex CLI",
  "/fr/guides/codex-desktop": "Codex Desktop",
  "/fr/guides/flatkey-cli": "CLI Flatkey avec agent IA",
  "/fr/guides/image-generation": "Génération et modification d'images",
  "/fr/guides/minimax-h3": "MiniMax H3",
  "/fr/guides/openai-sdk": "SDK OpenAI",
  "/fr/guides/seedance": "Seedance",
  "/fr/guides/text-generation": "Génération de texte",
  "/fr/guides/video-generation": "Génération de vidéo",
  "/fr/introduction": "Introduction",
  "/fr/quickstart": "Démarrage rapide",
  "/fr/reference/enterprise": "Entreprise",
  "/fr/reference/faq": "FAQ",
  "/fr/reference/model-health": "Santé des modèles",
  "/fr/reference/model-list": "Liste des modèles",
  "/fr/reference/pricing": "Tarification",
  "/guides/anthropic-sdk": "Anthropic SDK",
  "/guides/api-access": "API Access",
  "/guides/claude-code": "Claude Code",
  "/guides/codex-cli": "Codex CLI",
  "/guides/codex-desktop": "Codex Desktop",
  "/guides/flatkey-cli": "Flatkey CLI with AI Agent",
  "/guides/image-generation": "Image Generation & Editing",
  "/guides/minimax-h3": "MiniMax H3",
  "/guides/openai-sdk": "OpenAI SDK",
  "/guides/seedance": "Seedance",
  "/guides/text-generation": "Text Generation",
  "/guides/video-generation": "Video Generation",
  "/id": "Beranda",
  "/id/api-reference/authentication": "Autentikasi",
  "/id/api-reference/chat-completions": "Chat Completions",
  "/id/api-reference/embeddings": "Embeddings",
  "/id/api-reference/errors": "Kesalahan",
  "/id/api-reference/image-generation": "Images API",
  "/id/api-reference/models": "Model",
  "/id/api-reference/overview": "Ikhtisar",
  "/id/api-reference/responses": "Responses",
  "/id/api-reference/seedance-video-generation": "Pembuatan Video Seedance",
  "/id/dashboard/api-keys": "API Keys",
  "/id/dashboard/top-up": "Isi Saldo",
  "/id/dashboard/usage": "Penggunaan",
  "/id/guides/anthropic-sdk": "Anthropic SDK",
  "/id/guides/api-access": "Akses API",
  "/id/guides/claude-code": "Claude Code",
  "/id/guides/codex-cli": "Codex CLI",
  "/id/guides/codex-desktop": "Codex Desktop",
  "/id/guides/flatkey-cli": "Flatkey CLI dengan Agen AI",
  "/id/guides/image-generation": "Pembuatan & Pengeditan Gambar",
  "/id/guides/minimax-h3": "MiniMax H3",
  "/id/guides/openai-sdk": "OpenAI SDK",
  "/id/guides/seedance": "Seedance",
  "/id/guides/text-generation": "Pembuatan Teks",
  "/id/guides/video-generation": "Pembuatan Video",
  "/id/introduction": "Pengantar",
  "/id/quickstart": "Mulai Cepat",
  "/id/reference/enterprise": "Enterprise",
  "/id/reference/faq": "FAQ",
  "/id/reference/model-health": "Kesehatan Model",
  "/id/reference/model-list": "Daftar Model",
  "/id/reference/pricing": "Harga",
  "/introduction": "Introduction",
  "/ja": "ホーム",
  "/ja/api-reference/authentication": "認証",
  "/ja/api-reference/chat-completions": "Chat Completions",
  "/ja/api-reference/embeddings": "Embeddings",
  "/ja/api-reference/errors": "エラー",
  "/ja/api-reference/image-generation": "Images API",
  "/ja/api-reference/models": "モデル",
  "/ja/api-reference/overview": "概要",
  "/ja/api-reference/responses": "Responses",
  "/ja/api-reference/seedance-video-generation": "Seedance 動画生成",
  "/ja/dashboard/api-keys": "APIキー",
  "/ja/dashboard/top-up": "チャージ",
  "/ja/dashboard/usage": "使用状況",
  "/ja/guides/anthropic-sdk": "Anthropic SDK",
  "/ja/guides/api-access": "APIアクセス",
  "/ja/guides/claude-code": "Claude Code",
  "/ja/guides/codex-cli": "Codex CLI",
  "/ja/guides/codex-desktop": "Codex Desktop",
  "/ja/guides/flatkey-cli": "AIエージェントとFlatkey CLI",
  "/ja/guides/image-generation": "画像生成・編集",
  "/ja/guides/minimax-h3": "MiniMax H3",
  "/ja/guides/openai-sdk": "OpenAI SDK",
  "/ja/guides/seedance": "Seedance",
  "/ja/guides/text-generation": "テキスト生成",
  "/ja/guides/video-generation": "動画生成",
  "/ja/introduction": "はじめに",
  "/ja/quickstart": "クイックスタート",
  "/ja/reference/enterprise": "エンタープライズ",
  "/ja/reference/faq": "FAQ",
  "/ja/reference/model-health": "モデルの健全性",
  "/ja/reference/model-list": "モデル一覧",
  "/ja/reference/pricing": "料金",
  "/pt": "Início",
  "/pt/api-reference/authentication": "Autenticação",
  "/pt/api-reference/chat-completions": "Chat Completions",
  "/pt/api-reference/embeddings": "Embeddings",
  "/pt/api-reference/errors": "Erros",
  "/pt/api-reference/image-generation": "API de Imagens",
  "/pt/api-reference/models": "Modelos",
  "/pt/api-reference/overview": "Visão Geral",
  "/pt/api-reference/responses": "Responses",
  "/pt/api-reference/seedance-video-generation": "Geração de Vídeo Seedance",
  "/pt/dashboard/api-keys": "Chaves de API",
  "/pt/dashboard/top-up": "Adicionar Saldo",
  "/pt/dashboard/usage": "Uso",
  "/pt/guides/anthropic-sdk": "SDK Anthropic",
  "/pt/guides/api-access": "Acesso via API",
  "/pt/guides/claude-code": "Claude Code",
  "/pt/guides/codex-cli": "Codex CLI",
  "/pt/guides/codex-desktop": "Codex Desktop",
  "/pt/guides/flatkey-cli": "CLI da Flatkey com Agente de IA",
  "/pt/guides/image-generation": "Geração e Edição de Imagens",
  "/pt/guides/minimax-h3": "MiniMax H3",
  "/pt/guides/openai-sdk": "SDK da OpenAI",
  "/pt/guides/seedance": "Seedance",
  "/pt/guides/text-generation": "Geração de Texto",
  "/pt/guides/video-generation": "Geração de Vídeo",
  "/pt/introduction": "Introdução",
  "/pt/quickstart": "Início Rápido",
  "/pt/reference/enterprise": "Empresas",
  "/pt/reference/faq": "FAQ",
  "/pt/reference/model-health": "Saúde do Modelo",
  "/pt/reference/model-list": "Lista de Modelos",
  "/pt/reference/pricing": "Preços",
  "/quickstart": "Quickstart",
  "/reference/enterprise": "Enterprise",
  "/reference/faq": "FAQ",
  "/reference/model-health": "Model Health",
  "/reference/model-list": "Model List",
  "/reference/pricing": "Pricing",
  "/ru": "Главная",
  "/ru/api-reference/authentication": "Аутентификация",
  "/ru/api-reference/chat-completions": "Chat Completions",
  "/ru/api-reference/embeddings": "Embeddings",
  "/ru/api-reference/errors": "Ошибки",
  "/ru/api-reference/image-generation": "Images API",
  "/ru/api-reference/models": "Модели",
  "/ru/api-reference/overview": "Обзор",
  "/ru/api-reference/responses": "Responses",
  "/ru/api-reference/seedance-video-generation": "Генерация видео Seedance",
  "/ru/dashboard/api-keys": "API-ключи",
  "/ru/dashboard/top-up": "Пополнение",
  "/ru/dashboard/usage": "Использование",
  "/ru/guides/anthropic-sdk": "Anthropic SDK",
  "/ru/guides/api-access": "Доступ через API",
  "/ru/guides/claude-code": "Claude Code",
  "/ru/guides/codex-cli": "Codex CLI",
  "/ru/guides/codex-desktop": "Codex Desktop",
  "/ru/guides/flatkey-cli": "Flatkey CLI с ИИ-агентом",
  "/ru/guides/image-generation": "Генерация и редактирование изображений",
  "/ru/guides/minimax-h3": "MiniMax H3",
  "/ru/guides/openai-sdk": "OpenAI SDK",
  "/ru/guides/seedance": "Seedance",
  "/ru/guides/text-generation": "Генерация текста",
  "/ru/guides/video-generation": "Генерация видео",
  "/ru/introduction": "Введение",
  "/ru/quickstart": "Быстрый старт",
  "/ru/reference/enterprise": "Enterprise",
  "/ru/reference/faq": "FAQ",
  "/ru/reference/model-health": "Состояние моделей",
  "/ru/reference/model-list": "Список моделей",
  "/ru/reference/pricing": "Цены",
  "/vi": "Trang chủ",
  "/vi/api-reference/authentication": "Xác thực",
  "/vi/api-reference/chat-completions": "Chat Completions",
  "/vi/api-reference/embeddings": "Embeddings",
  "/vi/api-reference/errors": "Lỗi",
  "/vi/api-reference/image-generation": "Images API",
  "/vi/api-reference/models": "Models",
  "/vi/api-reference/overview": "Tổng quan",
  "/vi/api-reference/responses": "Responses",
  "/vi/api-reference/seedance-video-generation": "Tạo Video Seedance",
  "/vi/dashboard/api-keys": "Khóa API",
  "/vi/dashboard/top-up": "Nạp Tiền",
  "/vi/dashboard/usage": "Sử dụng",
  "/vi/guides/anthropic-sdk": "Anthropic SDK",
  "/vi/guides/api-access": "Truy cập API",
  "/vi/guides/claude-code": "Claude Code",
  "/vi/guides/codex-cli": "Codex CLI",
  "/vi/guides/codex-desktop": "Codex Desktop",
  "/vi/guides/flatkey-cli": "Flatkey CLI với AI Agent",
  "/vi/guides/image-generation": "Tạo & Chỉnh Sửa Hình Ảnh",
  "/vi/guides/minimax-h3": "MiniMax H3",
  "/vi/guides/openai-sdk": "OpenAI SDK",
  "/vi/guides/seedance": "Seedance",
  "/vi/guides/text-generation": "Tạo Văn Bản",
  "/vi/guides/video-generation": "Tạo Video",
  "/vi/introduction": "Giới thiệu",
  "/vi/quickstart": "Bắt đầu nhanh",
  "/vi/reference/enterprise": "Doanh nghiệp",
  "/vi/reference/faq": "FAQ",
  "/vi/reference/model-health": "Tình Trạng Model",
  "/vi/reference/model-list": "Danh Sách Mô Hình",
  "/vi/reference/pricing": "Bảng giá",
  "/zh": "首页",
  "/zh/api-reference/authentication": "认证",
  "/zh/api-reference/chat-completions": "对话补全",
  "/zh/api-reference/embeddings": "嵌入",
  "/zh/api-reference/errors": "错误",
  "/zh/api-reference/image-generation": "图片 API",
  "/zh/api-reference/models": "模型",
  "/zh/api-reference/overview": "概览",
  "/zh/api-reference/responses": "Responses",
  "/zh/api-reference/seedance-video-generation": "Seedance 视频生成",
  "/zh/dashboard/api-keys": "API 密钥",
  "/zh/dashboard/top-up": "充值",
  "/zh/dashboard/usage": "使用日志",
  "/zh/guides/anthropic-sdk": "Anthropic SDK",
  "/zh/guides/api-access": "API 接入",
  "/zh/guides/claude-code": "Claude Code",
  "/zh/guides/codex-cli": "Codex CLI",
  "/zh/guides/codex-desktop": "Codex 桌面端",
  "/zh/guides/flatkey-cli": "Flatkey CLI 与 AI Agent",
  "/zh/guides/image-generation": "图片生成与编辑",
  "/zh/guides/minimax-h3": "MiniMax H3",
  "/zh/guides/openai-sdk": "OpenAI SDK",
  "/zh/guides/seedance": "Seedance",
  "/zh/guides/text-generation": "文本生成",
  "/zh/guides/video-generation": "视频生成",
  "/zh/introduction": "简介",
  "/zh/quickstart": "快速开始",
  "/zh/reference/enterprise": "企业版",
  "/zh/reference/faq": "常见问题",
  "/zh/reference/model-health": "模型健康度",
  "/zh/reference/model-list": "模型列表",
  "/zh/reference/pricing": "价格",
};

const routeOf = (anchor) => {
  try {
    return new URL(anchor.href, window.location.origin).pathname.replace(/\/+$/, "") || "/";
  } catch {
    return null;
  }
};

const relabelPagination = () => {
  for (const anchor of document.querySelectorAll(
    "a.pagination-prev, a.pagination-next",
  )) {
    const label = SIDEBAR_TITLES[routeOf(anchor)];
    if (!label) continue;
    const title = anchor.querySelector(":scope > div > div:first-child");
    if (title && title.textContent !== label) title.textContent = label;
  }
};

let queued = false;
const schedule = () => {
  if (queued) return;
  queued = true;
  setTimeout(() => {
    queued = false;
    relabelPagination();
  }, 0);
};

// Mintlify loads this from <head>, and the pagination is rendered client side
// on every route change, so watch the document rather than running once.
new MutationObserver(schedule).observe(document.documentElement, {
  childList: true,
  subtree: true,
});
schedule();
